#!/usr/bin/env zsh

pushd $DOTFILES

for folder in ${(s:,:)STOW_FOLDERS}; do
    echo "Removing ~/.config/$folder"
    stow -D -t "$HOME/.config/$folder" "$folder"
done

popd

# Then uninstall all Homebrew packages including stow
if command -v brew >/dev/null 2>&1; then
  echo "Uninstalling all Homebrew packages..."
  brew list -1 | xargs -r brew uninstall --force

  echo "Running Homebrew uninstall script..."
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)"
else
  echo "Homebrew not installed. Skipping..."
fi
