#!/usr/bin/env zsh

pushd $DOTFILES

for folder in ${(s:,:)STOW_FOLDERS}; do
    echo "Removing ~/.config/$folder"
    stow -D -t "$HOME/.config/$folder" "$folder"
done

popd
echo "Cleaning up git configuration..."
rm -f $HOME/.gitconfig
rm -f $HOME/.gitignore_global
rm -rf $HOME/.config/git
echo "unset git settings..."
unset GIT_CONFIG_GLOBAL
unset GIT_DIR
unset GIT_WORK_TREE
git config --global url."https://github.com/".insteadOf git@github.com:
