#!/usr/bin/env zsh
if ! command -v brew >/dev/null 2>&1; then
 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
 eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
fi
brew update
brew bundle --file ./brew/Brewfile

echo "remove all existing .zsh files..."
rm -f $HOME/.zshrc $HOME/.zshenv $HOME/.zprofile $HOME/.zlogin
zshenv_path="$HOME/.zshenv"
echo 'export ZDOTDIR="$HOME/.dotfiles/zsh"' > "$zshenv_path"
echo "new .zshenv created at $zshenv_path with ZDOTDIR set to ~/.dotfiles/zsh"


if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="nvim,oh-my-posh,zsh,git"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/.dotfiles
fi

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install
