#!/usr/bin/env zsh

zshenv_path="$HOME/.zshenv"
echo 'export ZDOTDIR="$HOME/.dotfiles/zsh"' > "$zshenv_path"
echo ".zshenv created at $zshenv_path with ZDOTDIR set to ~/.dotfiles/zsh"


if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="nvim,oh-my-posh,zsh"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/.dotfiles
fi

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install
