
exec-once = hypridle
exec-once = mako
exec-once = waybar
exec-once = fcitx5
exec-once = elephant
exec-once = ~/.config/hypr/set-wallpapers.sh
exec-once = swayosd-server

exec-once = systemctl --user import-environment $(env | cut -d'=' -f 1)
exec-once = dbus-update-activation-environment --systemd --all
