#!/usr/bin/env zsh
PACKAGES=(
 stow
 ghostty
 nvim
 oh-my-posh
 zsh
 git
 hypr
 fzf
 dunst
 wlogout
 tofi
 waybar
 grimblast-git
)
export PACKAGES
export STOW_FOLDERS="assets,ghostty,nvim,oh-my-posh,zsh,git,hypr,waybar,tofi,dunst,wlogout"


