#!/usr/bin/env zsh
PACKAGES=(
 stow
 ghostty
 nvim
 oh-my-posh
 zsh
 git
 hypr
 fzf
 fd
 btop
 tofi
 waybar
 swayosd
 swaybg
 blueberry
 grimblast-git
 power-profiles-daemon
 impala
 libinput 
 mise
 imv
 walker
)
export PACKAGES
export STOW_FOLDERS="assets,ghostty,nvim,oh-my-posh,zsh,git,hypr,waybar,tofi,dunst,swayosd,btop,fzf,mise,imv"


