
theme[main_bg]=""

theme[main_fg]="#EAEAEA"

theme[title]="#8a8a8d"

theme[hi_fg]="#f59e0b"

theme[selected_bg]="#f59e0b"

theme[selected_fg]="#EAEAEA"

theme[inactive_fg]="#333333"

theme[proc_misc]="#8a8a8d"

theme[cpu_box]="#8a8a8d"

theme[mem_box]="#8a8a8d"

theme[net_box]="#8a8a8d"

theme[proc_box]="#8a8a8d"

theme[div_line]="#8a8a8d"

theme[temp_start]="#8a8a8d"
theme[temp_mid]="#f59e0b"
theme[temp_end]="#b91c1c"

theme[cpu_start]="#8a8a8d"
theme[cpu_mid]="#f59e0b"
theme[cpu_end]="#b91c1c"

theme[free_start]="#8a8a8d"
theme[free_mid]="#f59e0b"
theme[free_end]="#b91c1c"

theme[cached_start]="#8a8a8d"
theme[cached_mid]="#f59e0b"
theme[cached_end]="#b91c1c"

theme[available_start]="#8a8a8d"
theme[available_mid]="#f59e0b"
theme[available_end]="#b91c1c"

theme[used_start]="#8a8a8d"
theme[used_mid]="#f59e0b"
theme[used_end]="#b91c1c"

theme[download_start]="#8a8a8d"
theme[download_mid]="#f59e0b"
theme[download_end]="#b91c1c"

theme[upload_start]="#8a8a8d"
theme[upload_mid]="#f59e0b"
theme[upload_end]="#b91c1c"
